export const MORPH_WORDS = [
  { text: 'an applied linguist', cls: 'w-lang' },
  { text: 'an energy strategist', cls: 'w-energy' },
  { text: 'a director of education', cls: 'w-teach' },
  { text: 'a classroom storyteller', cls: 'w-lang' },
  { text: 'a decarbonization writer', cls: 'w-energy' },
  { text: 'a curriculum designer', cls: 'w-teach' },
  { text: 'a recovering academic', cls: 'w-writer' },
  { text: 'a cruciverbalist', cls: 'w-writer' },
  { text: 'a language lover', cls: 'w-lang' },
];

export const NOW_ITEMS = [
  'Finalizing the first series for the "Language and Power" blog',
  'Drafting a paper on incorporating EMI in Brazil',
  'Managing the publication Staying Current for Evolved Energy Research',
  'Designing an energy themed crossword',
];

export const TIMELINE = [
  {
    id: 'eer', year: '2024 — Now', role: 'Director of Education',
    place: 'Evolved Energy Research · San Diego', current: true, badge: 'Current',
    bullets: [
      'Lead internal education efforts: training, curriculum, onboarding for new staff across engineering and policy teams.',
      'Run external education: newsletters, blog posts, press releases, news articles translating modeling work for non-modelers.',
      'Write and co-author technical reports, including EER\'s 2024 Annual Decarbonization Perspective in Europe and dozens of client deliverables.',
      'Bridge the firm\'s quantitative research and the public-facing voice of the practice.',
    ],
  },
  {
    id: 'dos', year: '2023 — 2024', role: 'English Language Fellow',
    place: 'U.S. Department of State', current: false, badge: 'Diplomat',
    bullets: [
      'Represented the United States as a visiting scholar and English-language expert at the University of São Paulo.',
      'Recruited local scholars for English language teaching conferences.',
      'Delivered keynotes and seminars to train teachers across the region.',
      'Expanded access to equitable education across classes and cultures through diverse outreach.',
    ],
  },
  {
    id: 'usp', year: '2023 — 2024', role: 'Visiting Professor',
    place: 'Universidade de São Paulo · Brazil', current: false, badge: 'Faculty',
    bullets: [
      'Designed curricula and taught Linguistics, Applied Linguistics, and English at the top university in Latin America.',
      'Led English as a Medium of Instruction (EMI) conferences and workshops for 50+ professors across Brazil.',
      'Instructed an online EMI course for over 100 professors shifting from Portuguese to English.',
      'Mentored dozens of scholars on papers for publication at the LLAC campus language lab.',
    ],
  },
  {
    id: 'ucla', year: '2017 — 2020', role: 'Lecturer',
    place: 'UCLA · Los Angeles', current: false, badge: 'Faculty',
    bullets: [
      'Full-time lecturer in Applied Linguistics, Linguistics, and ESL — academic writing and language studies.',
      'Designed syllabi, selected readings, facilitated discussion, held office hours.',
      'Oversaw courses of 15 – 88 students per lecture; 500+ students total.',
      'Managed, observed, and mentored up to four TAs per course.',
    ],
  },
  {
    id: 'phd', year: '2009 — 2017', role: 'PhD · Applied Linguistics',
    place: 'UCLA · Los Angeles', current: false, badge: 'Doctorate',
    bullets: [
      'Dissertation: "Measuring Linguistic Empathy — an experimental approach to connecting linguistic and social-psychological notions of empathy."',
      'Designed and administered behavioral + EEG psycholinguistic experiments.',
      'Taught as Teaching Associate, TA, and Instructor; 400+ students across sections.',
      'Assistant Editor, Issues in Applied Linguistics; Student Rep for the department.',
    ],
  },
  {
    id: 'korea', year: '2006', role: 'English Instructor',
    place: 'South Korea', current: false, badge: 'Early career',
    bullets: [
      'Tutored high school students in English language and academic skills.',
      'Freelanced as an English instructor at a Korean university.',
      'First professional teaching experience abroad — left to pursue graduate study at UCLA.',
    ],
  },
  {
    id: 'smc', year: '2012 — 2013', role: 'Adjunct Professor',
    place: 'Santa Monica College · ESL', current: false, badge: 'Early career',
    bullets: [
      'Instructor in the Department of English as a Second Language.',
      'Designed syllabi, selected materials, wrote essay prompts and testing materials.',
      'Facilitated discussion, interaction, and presentations for 50+ students.',
    ],
  },
];

export const COURSES = [
  { code: 'LING 1',      title: 'The Study of Language',                        where: 'UCLA',              cat: 'ling' },
  { code: 'LING 9W',     title: 'Linguistic Humor — Amusing & Abusing with Language', where: 'UCLA',        cat: 'ling' },
  { code: 'LING 11',     title: 'Language in Action — Applied Linguistics',      where: 'UCLA',              cat: 'ling' },
  { code: 'LING 20',     title: 'Introduction to Linguistic Analysis',           where: 'UCLA',              cat: 'ling' },
  { code: 'LING 144',    title: 'Fundamentals in Translation & Interpreting',    where: 'UCLA',              cat: 'ling' },
  { code: 'LING 170',    title: 'Language & Society — Sociolinguistics',         where: 'UCLA',              cat: 'ling' },
  { code: 'USP',         title: 'Topics of Semantics',                           where: 'São Paulo',         cat: 'ling' },
  { code: 'USP',         title: 'Phonetics & Phonology',                         where: 'São Paulo',         cat: 'ling' },
  { code: 'APPLING 30W', title: 'Language & Social Interaction',                 where: 'UCLA',              cat: 'appling' },
  { code: 'APPLING 40W', title: 'Language & Gender',                             where: 'UCLA',              cat: 'appling' },
  { code: 'APPLING 101W',title: 'Language Learning & Teaching',                  where: 'UCLA',              cat: 'appling' },
  { code: 'APPLING 102W',title: 'The Nature of Language',                        where: 'UCLA',              cat: 'appling' },
  { code: 'APPLING 161W',title: 'Talk and the Body',                             where: 'UCLA · cross-listed Anthro', cat: 'appling' },
  { code: 'USP',         title: 'Topics in Discourse Analysis',                  where: 'São Paulo',         cat: 'appling' },
  { code: 'EMI',         title: 'English as a Medium of Instruction',            where: 'USP + U.S. DoS · online', cat: 'appling' },
  { code: 'ESL 28',      title: 'English Through Language, Culture & Society',  where: 'UCLA',              cat: 'esl' },
  { code: 'ESL 33C',     title: 'Academic Writing',                              where: 'UCLA',              cat: 'esl' },
  { code: 'ESL 34',      title: 'Public Speaking',                               where: 'UCLA',              cat: 'esl' },
  { code: 'ESL 38B',     title: 'Pronunciation',                                 where: 'UCLA',              cat: 'esl' },
  { code: 'Anderson',    title: 'Business English — Speaking/Listening',         where: 'UCLA Anderson',     cat: 'esl' },
  { code: 'USP',         title: 'Academic Writing',                              where: 'São Paulo',         cat: 'esl' },
];

export const TESTIMONIALS = [
  { quote: "Thanks for sharing your knowledge and jokes with us!", author: 'Paulo · USP 2024', lang: 'EN' },
  { quote: "Obrigada pelo semestre — você é um professor cativante.", author: 'Júlia · USP 2023', lang: 'PT' },
  { quote: "Love the style of your teaching. As students, we enjoy inexhaustible knowledge and a facetious professor at the same time.", author: 'UCLA Linguistics 170', lang: 'EN' },
  { quote: "感谢 Trevor, 祝一切好 — thank you for this great semester!", author: 'Junzilan · USP 2024', lang: 'ZH' },
  { quote: "Thank you for being the best teacher in my life. A lot more appreciated than I can say.", author: 'UCLA ESL student', lang: 'EN' },
  { quote: "Obrigado pelas aulas incríveis desse semestre. Todo de bom!", author: 'Gustavo · USP 2023', lang: 'PT' },
  { quote: "By far, Mr. Trevor has been the best T.A. in any class I have attended here at UCLA — and this is my last quarter here. He has been very fun, approachable, supportive, very useful, and has made this otherwise tedious class very enjoyable and useful to me. Writing has always been a daunting task for me but Trevor has made writing manageable, logical, and fun.", author: 'UCLA Applied Linguistics · 2011', lang: 'EN', span: true },
];

export const ETYM_WORDS = [
  { w: 'power',      ipa: '/ˈpaʊ.ər/',        roots: 'O.Fr. poeir, from L. potere — to be able',
    both: ['Language: who holds authority in speech; whose words carry weight.', 'Energy: the rate at which work is done.', 'Both: what is this agent able to cause?'] },
  { w: 'current',    ipa: '/ˈkʌr.ənt/',        roots: 'L. currere — to run',
    both: ['Discourse: shared context {you, me, here, now} and what flows in speech right now.', 'Electrical: flow of charge through a conductor.', 'Both: something running past.'] },
  { w: 'charge',     ipa: '/tʃɑːrdʒ/',          roots: 'L. carricare — to load a cart',
    both: ['Language: to invest with meaning — "charged language," loaded words.', 'Energy: a quantity of electric potential.', 'Both: loading something up until it releases.'] },
  { w: 'capacity',   ipa: '/kəˈpæs.ɪ.ti/',     roots: 'L. capax — able to hold',
    both: ['Linguistic: the uniquely human drive to engage with others through language.', 'Grid: installed potential available to meet demand.', 'Both: what a system can do when called upon.'] },
  { w: 'grid',       ipa: '/ɡrɪd/',             roots: 'Back-formation from *gridiron*, O.E. grædig',
    both: ['Language: crossword grids, orthographic grids, morphological paradigms.', 'Electrical: the synchronized transmission network.', 'Both: structures that make interconnection visible.'] },
  { w: 'fluency',    ipa: '/ˈfluː.ən.si/',      roots: 'L. fluere — to flow',
    both: ['Language: flow of speech without effort.', 'Energy: thermal and fluid dynamics — literal flow.', 'Both: the root fluere doing double duty.'] },
  { w: 'transition', ipa: '/trænˈzɪʃ.ən/',      roots: 'L. transitionem, from trans- + ire — a going across',
    both: ['Conversation: the moment, cued by grammar and prosody, when a speaker yields the floor.', 'Energy: from fossil fuels to a decarbonized system.', 'Both: a managed handoff from one state to another.'] },
  { w: 'code',       ipa: '/koʊd/',             roots: 'L. codex — wooden tablet, book',
    both: ['Language: the repertoire speakers shift between across social contexts.', 'Energy: the programming languages that translate real-world systems into computable form.', 'Both: governed by rules that shape what\'s possible.'] },
  { w: 'voice',      ipa: '/vɔɪs/',             roots: 'L. vox — voice, word',
    both: ['Language: active/passive voice — who does what to whom.', 'Energy: how a utility or regulator is heard in policy.', 'Both: grammar and rhetoric ask who the agent is.'] },
  { w: 'frame',      ipa: '/freɪm/',            roots: 'O.E. framian — to be helpful',
    both: ['Language: the interpretive structure that organizes what a situation means.', 'Energy: the frame around a project shapes which evidence counts.', 'Both: everything depends on how we bracket the question.'] },
];

export const CONCEPT_NODES = [
  { id: 'ling',       label: 'Linguistics',       type: 'ling',   x: 18, y: 30, size: 1.0 },
  { id: 'discourse',  label: 'Discourse',         type: 'ling',   x: 10, y: 50 },
  { id: 'framing',    label: 'Framing',           type: 'ling',   x: 8,  y: 72 },
  { id: 'register',   label: 'Register',          type: 'ling',   x: 22, y: 78 },
  { id: 'pragmatics', label: 'Pragmatics',        type: 'ling',   x: 28, y: 64 },
  { id: 'empathy',    label: 'Empathy',           type: 'ling',   x: 16, y: 16 },
  { id: 'teaching',   label: 'Teaching',          type: 'ling',   x: 30, y: 40 },
  { id: 'energy',     label: 'Energy planning',   type: 'energy', x: 82, y: 30, size: 1.0 },
  { id: 'grid',       label: 'Grid',              type: 'energy', x: 88, y: 50 },
  { id: 'decarb',     label: 'Decarbonization',   type: 'energy', x: 90, y: 72 },
  { id: 'policy',     label: 'Policy',            type: 'energy', x: 78, y: 78 },
  { id: 'model',      label: 'RIO / ENSEMBLE',    type: 'energy', x: 72, y: 64 },
  { id: 'transition', label: 'Transition',         type: 'bridge', x: 50, y: 18 },
  { id: 'utility',    label: 'Utility',           type: 'energy', x: 70, y: 40 },
  { id: 'scenario',   label: 'Scenario',          type: 'energy', x: 84, y: 16 },
  { id: 'power',      label: 'Power',             type: 'bridge', x: 48, y: 36 },
  { id: 'current',    label: 'Current',           type: 'bridge', x: 52, y: 54 },
  { id: 'capacity',   label: 'Capacity',          type: 'bridge', x: 48, y: 72 },
  { id: 'translation',label: 'Translation',       type: 'ling',   x: 32, y: 26 },
  { id: 'code',       label: 'Code',              type: 'bridge', x: 52, y: 84 },
];

export const CONCEPT_EDGES: [string, string][] = [
  ['ling','discourse'],['ling','teaching'],['ling','empathy'],['ling','pragmatics'],['ling','transition'],
  ['discourse','framing'],['discourse','pragmatics'],
  ['framing','register'],['pragmatics','teaching'],
  ['empathy','teaching'],['empathy','pragmatics'],['empathy','discourse'],['empathy','translation'],['register','teaching'],
  ['energy','grid'],['energy','utility'],['energy','scenario'],
  ['transition','ling'],['transition','discourse'],['transition','energy'],
  ['empathy','energy'],
  ['grid','decarb'],['grid','capacity'],['decarb','policy'],['decarb','transition'],['policy','model'],['policy','teaching'],
  ['model','utility'],['transition','model'],
  ['scenario','model'],['scenario','energy'],['scenario','transition'],['scenario','discourse'],['scenario','pragmatics'],
  ['power','ling'],['power','energy'],['power','framing'],['power','grid'],
  ['current','discourse'],['current','grid'],['current','register'],['current','utility'],
  ['capacity','teaching'],['capacity','model'],['capacity','empathy'],['capacity','decarb'],
  ['translation','ling'],['translation','register'],['translation','empathy'],
  ['code','framing'],['code','model'],['code','policy'],['code','pragmatics'],['code','register'],
  ['framing','policy'],['utility','policy'],['discourse','register'],
  ['framing','decarb'],['register','utility'],['pragmatics','policy'],['discourse','energy'],['framing','grid'],
];

export const CAPTIONS: Record<string, string> = {
  power: '<b>Power</b> — Sociolinguistic power (dominance or influence asserted through language choices, accent, and style) and electrical power (rate of energy transfer) both describe what an agent is able to cause.',
  current: '<b>Current</b> — in discourse, shared context {you, me, here, now} and what flows in speech right now. On a grid: what flows through a conductor.',
  capacity: '<b>Capacity</b> — the uniquely human drive to engage with others through language. In energy, the installed potential available to meet demand.',
  translation: '<b>Translation</b> — in language, the transfer of meaning across languages and sociolinguistic contexts — never perfectly symmetrical.',
  scenario: '<b>Scenario</b> — in energy planning, a structured representation of how the future energy system might evolve under different assumptions. In linguistics, the framing of a possible world that shapes how an argument is received.',
  code: '<b>Code</b> — in language, the repertoire speakers shift between across social contexts: languages, dialects, registers, identities. In energy, the programming and modeling languages that translate real-world systems into computable form.',
  ling: '<b>Linguistics</b> — the study of language in use: how people build meaning together across communities, institutions, and power structures. The academic foundation behind everything else on this map.',
  energy: '<b>Energy</b> — in planning, how power is generated, transmitted, and consumed across a decarbonized system. In phonetics, the acoustic force behind stress, rhythm, and intonation; in social interaction, what every exchange expends.',
  grid: '<b>Grid</b> — in language, the underlying structure that organizes a system: morphological paradigms, orthographic grids, crossword grids. In energy, the synchronized transmission network that connects generation to demand.',
  decarb: '<b>Decarbonization</b> — the systematic removal of carbon from the power sector through renewables, efficiency, and storage. The goal the rest of this map is working toward.',
  utility: '<b>Utility</b> — in linguistics, the functional value of a linguistic form: what it does in context. In energy, the regulated companies that own and operate the infrastructure delivering power to homes and businesses.',
  policy: '<b>Policy</b> — in language, the institutionalized rules that govern whose speech counts and in what contexts. In energy, the regulatory and legislative framework that shapes what gets built, by whom, and at what cost.',
  empathy: '<b>Empathy</b> — in language, perspective encoded in grammar and felt in conversation. In energy planning, understanding how different communities and stakeholders experience the energy transition.',
  framing: '<b>Framing</b> — in discourse, the interpretive lens that allows individuals to interpret what a situation or conversation truly means. In energy, the frame around a project — capacity, emissions, cost, policy — influences stakeholder interpretation of an analysis within a complex system.',
  register: '<b>Register</b> — in language, how speech shifts to fit its context: technical, formal, colloquial, urgent. In energy planning, navigating between the language of models, policy, and public engagement means operating in several registers at once.',
  pragmatics: '<b>Pragmatics</b> — meaning in use: what\'s implied, presupposed, and left to inference. In energy, the same transition gets called \'grid modernization,\' \'climate action,\' or \'energy security\' depending on the room.',
  model: '<b>Model</b> — in linguistics, large language models are statistical representations of language patterns trained on vast amounts of human text. In energy, RIO and ENSEMBLE model the system we\'re trying to build.',
  transition: '<b>Transition</b> — in conversation analysis, the moment when one speaker yields the floor to another: precisely managed, cued by grammar and prosody. In energy, the shift to a decarbonized system is the defining infrastructure project of this century.',
  teaching: '<b>Teaching</b> — in language education, meeting learners where they are and building from there. In energy, the same challenge: making complex systems legible to the people who need to act on them.',
};
